version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - 'postgre-data:/var/lib/postgresql'
    ports:
      - '5432:5432'
    restart: 'no'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'taskmanagement'
volumes:
  postgre-data:
